### ISSUE TITLE
방명록 구현

### ISSUE THREAD

**Issue by kpryu6** [Kakao-X-Goorm-DEEP-DIVE-course/guestbook#3]
### 💼 작업 설명
**팀미션2** 
- 방명록 구현하기
  - Django
  - MySQL
  - Docker

### ✅ To-do
- [x] Django 튜토리얼 및 학습
- [x] Django로 방명록 구현 + MySQL 연동
- [x] Docker로 Django Web과 MySQL 컨테이너화
- [x] Demo
- [x] 발표자료
